# Generated by Django 2.2.4 on 2019-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_adminpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
