# Generated by Django 2.2.4 on 2019-09-04 04:34

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='age',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='cover',
            field=pyuploadcare.dj.models.ImageField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=pyuploadcare.dj.models.ImageField(blank=True, default=''),
        ),
    ]
