# Generated by Django 2.2.4 on 2019-09-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190904_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='sex',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='age',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(default='', max_length=50),
        ),
    ]
